### PR TITLE
move prepush to hooks section

### LINKED ISSUE #345: Question: do we need opt chain dependency
Since typescript 3.7, it has optional chain feature, and we're way past that, do we still need the optional chain dependency?

thoughts? @paibamboo

### PR DESCRIPTION
**Pull request by cyberhck**
closes #345

### CODE REVIEW

**Comment by paibamboo** [comment]
Ah I misunderstood your question, I thought you asked if `ts-optchain` could be removed. Since we use babel to transpile typescript, I'm not sure if removing this will break things. I will check it out.

**Comment by cyberhck** [comment]
I don't think we have ts-optchain anymore, but yeah, you're right, we might need the babel transformer, if we do need it, then I'll unchange that part, let me know (then I'll just do the moving of husky script)

**Comment by cyberhck** [comment]
@paibamboo , I've reverted that change, and now only the moving of prepush into hooks section, please review :)

**Comment by paibamboo** [comment]
Thanks Nishchal

**Pull request merged**
