### PR TITLE
ci(provider): move to github actions

### LINKED ISSUE #354: move to github actions
With the new hype of github actions, it'd be a really good idea to start using it for this project, my thought was to create 3 separate actions, one for linting, one for type check and last one for unit testing

### PR DESCRIPTION
**Pull request by cyberhck**
closes #354

### CODE REVIEW

**Comment by cyberhck** [comment]
image
image
(fixed the naming on second pass, we need to make this required now, and notice it's a bit faster)

**Comment by cyberhck** [comment]
needs codecov token for code coverage to work

**Comment by cyberhck** [comment]
one way is to add codecov to this repo's secret, another option is to go to organization's namespace so you can re-use that token in multiple repository

**Comment by cyberhck** [comment]
@paibamboo any update on how we should proceed here? I'm okay finding out with wrong method, but would rather see you getting the data from lastpass and saving on org level so we can use it :)

**Comment by paibamboo** [comment]
Codecov token is not in the lastpass. And March is still busy. Please go head with your wrong method :)

**Review by paibamboo — APPROVED** [review]

**Pull request merged**
